### PR TITLE
Made all overview pages show summary and added share buttons

### PR DESCRIPTION
**Pull request by yannickl88**
Changes:
- Made all overview pages show summary 
- added share buttons to post page
- Made banner on index bigger
- Added better meta descriptions for posts
- Tag overview shows only tagged blogs instead of all blogs

### CODE REVIEW

**Comment by yannickl88** [comment]
ping @iltar

**Comment by linaori** [comment]
Ah nice, got some screenshots?

**Comment by yannickl88** [comment]
sure:
Imgur
Imgur

**Comment by linaori** [comment]
Nice! :+1:

**Comment by linaori** [comment]
Oh the social icons are not aligned 100% :(

**Comment by yannickl88** [comment]
myeah.... I can't properly fix them. There is a bunch of javascript which is replacing the original element with an iframe and it seems to ignore any padding or margin...

**Comment by linaori** [comment]
:cry: ah well, LGTM

**Pull request merged**
